In [27]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_breast_cancer

from sdv.metadata import Metadata
from sdv.single_table import CTGANSynthesizer, TVAESynthesizer

In [36]:
df = load_breast_cancer(as_frame=True).frame

train, test = train_test_split(df, test_size=0.2)

metadata = Metadata.detect_from_dataframe(train, table_name='breast_cancer')
metadata.update_column('target',table_name='breast_cancer', sdtype='categorical')

metadata.save_to_json('breast_cancer_metadata.json')

CTGANsynthesizer = CTGANSynthesizer(metadata, epochs=100)
CTGANsynthesizer.fit(train)
TVAEsynthesizer = TVAESynthesizer(metadata, epochs=100)
TVAEsynthesizer.fit(train)

In [37]:
CTGANsynthetic = CTGANsynthesizer.sample(num_rows=len(train))
TVAEsynthetic = TVAEsynthesizer.sample(num_rows=len(train))

In [38]:
CTGANsynthetic

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.713,23.20,57.16,1457.0,0.06251,0.04755,0.008444,0.000000,0.1642,0.07623,...,29.71,244.11,277.1,0.12290,0.12912,0.000000,0.094667,0.1603,0.06959,1
1,16.205,29.38,136.80,1549.6,0.08618,0.05208,0.044993,0.048118,0.2027,0.07076,...,22.52,234.42,185.2,0.12847,0.53386,0.000000,0.006994,0.2799,0.07773,1
2,14.852,23.57,52.04,1428.1,0.06251,0.05917,0.079111,0.022810,0.1701,0.06824,...,40.46,144.15,185.2,0.10431,0.24126,0.000000,0.005576,0.2983,0.08955,1
3,18.090,28.25,56.61,349.4,0.07583,0.01938,0.199308,0.000000,0.1583,0.07105,...,30.52,129.17,901.2,0.13751,0.23270,0.440836,0.000000,0.3113,0.05521,0
4,16.314,22.58,70.70,663.5,0.07631,0.10290,0.311337,0.157781,0.1167,0.06918,...,34.48,169.54,865.2,0.15929,0.07718,0.144194,0.153821,0.2425,0.07869,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,15.875,29.40,68.52,398.1,0.06282,0.04459,0.085954,0.062831,0.1705,0.06615,...,31.83,206.76,499.0,0.14084,0.44038,0.351504,0.000000,0.2936,0.10396,0
451,18.461,23.00,66.05,1416.6,0.07484,0.10829,0.401109,0.047857,0.1167,0.07252,...,27.62,82.16,452.0,0.12293,0.32513,0.000000,0.179798,0.2015,0.08819,1
452,10.143,20.76,43.79,373.4,0.10489,0.01938,0.091470,0.097350,0.1411,0.06677,...,20.82,144.89,185.2,0.08489,0.19642,0.000000,0.043812,0.1644,0.06490,1
453,9.690,13.04,49.97,161.7,0.06251,0.02311,0.137214,0.040039,0.1242,0.07077,...,24.89,119.39,340.3,0.13069,0.32683,0.051356,0.110790,0.2259,0.06724,0
454,13.777,26.89,92.86,1467.3,0.07721,0.03192,0.032714,0.000000,0.1384,0.07100,...,18.17,131.09,368.3,0.11529,0.75326,0.095104,0.000000,0.2235,0.06576,1

In [39]:
TVAEsynthetic

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,10.918,21.98,87.41,338.8,0.09742,0.13344,0.046961,0.019632,0.1954,0.06176,...,26.65,84.94,435.8,0.12186,0.17858,0.067154,0.065506,0.2949,0.06987,1
1,13.095,17.56,84.13,617.4,0.08544,0.05133,0.038825,0.024114,0.1764,0.06126,...,26.37,76.33,491.7,0.12093,0.14772,0.119614,0.041888,0.2319,0.06712,1
2,11.413,17.15,78.51,396.1,0.08269,0.05874,0.055029,0.018128,0.1737,0.05934,...,24.96,76.69,394.1,0.12813,0.17358,0.097124,0.037797,0.2900,0.06577,1
3,11.998,18.20,70.21,688.1,0.10307,0.14032,0.183814,0.028003,0.1923,0.06052,...,31.22,74.91,660.5,0.15940,0.37536,0.375083,0.106376,0.2951,0.09335,1
4,12.167,18.30,75.03,554.2,0.08914,0.07017,0.013059,0.024172,0.1541,0.05920,...,30.51,75.35,659.6,0.11223,0.18907,0.202650,0.060402,0.2768,0.06124,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,12.459,18.97,81.52,495.0,0.08789,0.12225,0.024237,0.019840,0.1916,0.06035,...,32.01,84.69,682.6,0.14100,0.20748,0.006008,0.061997,0.2600,0.08886,1
451,12.938,20.00,145.59,554.0,0.09272,0.09778,0.039665,0.068461,0.1636,0.05948,...,24.22,125.38,644.0,0.10104,0.20845,0.347461,0.231175,0.2192,0.07627,1
452,12.031,18.78,70.53,403.8,0.11752,0.06442,0.036552,0.020400,0.1656,0.06607,...,25.67,65.71,695.0,0.13781,0.14089,0.133008,0.067186,0.2767,0.08581,1
453,11.341,16.39,91.80,472.0,0.08175,0.03651,0.000000,0.020306,0.1504,0.05677,...,22.10,89.58,532.5,0.10151,0.15181,0.083240,0.056016,0.2313,0.06366,1
454,20.667,19.96,127.68,931.7,0.10551,0.11401,0.192858,0.088635,0.1890,0.06368,...,33.04,155.72,1758.5,0.16653,0.32603,0.377705,0.223851,0.3022,0.07175,0

In [40]:
X_train, y_train = train.drop('target', axis=1), train.target
X_test, y_test = test.drop('target', axis=1), test.target
X_csyn, y_csyn = CTGANsynthetic.drop('target', axis=1), synthetic.target
X_tsyn, y_tsyn = TVAEsynthetic.drop('target', axis=1), synthetic.target

In [41]:
ccombined = pd.concat([train, CTGANsynthetic], ignore_index=True)
X_ccombined, y_ccombined = ccombined.drop('target', axis=1), ccombined.target
tcombined = pd.concat([train, TVAEsynthetic], ignore_index=True)
X_tcombined, y_tcombined = tcombined.drop('target', axis=1), tcombined.target

In [42]:
baseline = RandomForestClassifier()
baseline.fit(X_train, y_train)
baseline.score(X_test, y_test)

RandomForestClassifier()

In [44]:
ccombined_model = RandomForestClassifier()
ccombined_model.fit(X_ccombined, y_ccombined)
ccombined_model.score(X_test, y_test)

RandomForestClassifier()

In [46]:
tcombined_model = RandomForestClassifier()
tcombined_model.fit(X_tcombined, y_tcombined)
tcombined_model.score(X_test, y_test)

RandomForestClassifier()

In [48]:
csynthetic_model = RandomForestClassifier()
csynthetic_model.fit(X_csyn, y_csyn)
csynthetic_model.score(X_test, y_test)

0.30701754385964913

In [49]:
tsynthetic_model = RandomForestClassifier()
tsynthetic_model.fit(X_tsyn, y_tsyn)
tsynthetic_model.score(X_test, y_test)

0.631578947368421